watcher:
  watch_dir: /watch_dir
  results_dir: /results
  log_dir: /var/log/quarantine

celery_app:
  broker: redis://redis:6379/0
  backend: redis://redis:6379/1
  incoming: redis://redis:6379/2
  outgoing: redis://redis:6379/3
  task_soft_time_limit: 1
